#!/usr/bin/env python
import sys, getopt, os, subprocess, ConfigParser

def main(argv):
   command = ''
   master = True

   try:
      opts, args = getopt.getopt(argv,"hc:",["command=", "exclude-master"])
   except getopt.GetoptError:
      print 'ollin_script.py -c <command>'
      sys.exit(2)

   for opt, arg in opts:
      if opt == '-h':
         print 'ollin_script.py -c <command>'
         sys.exit()
      elif opt in ("-c", "--command"):
         command = arg
      elif opt == "--exclude-master":
         master = False
   
   if master:
      os.system(command)

   configParser = ConfigParser.RawConfigParser()
   configFilePath = "/etc/hpctools/config"
   configParser.read(configFilePath)

   nodes =  configParser.get('file', 'nodes').replace(" ", "")
   number_nodes = int(configParser.get('file', 'number_nodes'))


   for i in range(1, number_nodes + 1):
      subprocess.call(["ssh", nodes + "-" + str(i), command])

      


	
if __name__ == "__main__":
   main(sys.argv[1:])
