#!/usr/bin/env python

import sys, getopt, subprocess, ConfigParser

def main(argv):
   origin = ""
   destination = ""
   recursive = False
   try: 
      opts, args = getopt.getopt(argv,"hro:d:",["origin=", "destination="])
   except getopt.GetoptError:
      print 'copyFile2ollin.py -o <origin> -d <destination>'
      print 'For directories add -r'
      sys.exit(2)

   for opt, arg in opts:
      if opt == '-h':
         print 'copyFile2ollin.py -o <origin> -d <destination>'
         print 'copyFile2ollin.py -o <origin> -d <destination>'
      	 sys.exit()
      elif opt in ("-o", "--origin"):
         origin = arg
      elif opt in ("-d", "--destination"):
         destination = arg 
      elif opt == "-r":
         recursive = True

   configParser = ConfigParser.RawConfigParser()
   configFilePath = "/etc/hpctools/config"
   configParser.read(configFilePath)

   nodes =  configParser.get('file', 'nodes').replace(" ", "")
   number_nodes = int(configParser.get('file', 'number_nodes'))


   if recursive:
      for i in range(1, number_nodes + 1): 
         subprocess.call(["scp","-r", origin, nodes + "-" + str(i) + ":" + destination])
   else:
      for i in range(1, 11):
         subprocess.call(["scp", origin, nodes + "-" + str(i) + ":" + destination])

if __name__ == "__main__":
   main(sys.argv[1:])
